services:
  payment:
    image: serversideup/php:8.4-fpm-nginx-alpine
    ports:
      - "8081:8080"
    volumes:
      - .:/var/www/html

  api-db:
    image: mariadb:11
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: paymentapi

networks:
  default:
    name: my-network
    external: true